version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 12345:5432
    environment:
      - phonebookDB=DB
      - POSTGRES_USER=phonebookDB
      - POSTGRES_PASSWORD=phonebookDB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
